---
  - src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.13"
    name: clickhouse 

  - src: git@github.com:Arthur-Politiko/vector-ansible-role.git
    scm: git
    #version: "1.13"
    name: vector 

  - src: git@github.com:Arthur-Politiko/lighthouse-ansible-role.git
    scm: git
    #version: "1.13"
    name: lighthouse         